### ISSUE TITLE
cannot load extension in ipython 5.8 (python  3.7.3)

### ISSUE THREAD

**Issue by 400thecat** [birkenfeld/ipython-physics#1]
Hello,

I have been using your wonderful extension for many years, with and ipython 2.3 (python 2.7.3 )

Now I have switched to ipython 5.8 (python  3.7.3) and I get following error when trying to load the extension:

```
[TerminalIPythonApp] WARNING | Error in loading extension: physics
Check your config files in ~/.ipython/profile_default
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/IPython/core/shellapp.py", line 248, in init_extensions
    self.shell.extension_manager.load_extension(ext)
  File "/usr/lib/python3/dist-packages/IPython/core/extensions.py", line 83, in load_extension
    __import__(module_str)
  File "~/.ipython/extensions/physics.py", line 21
    def valuetype((v, u)):
                  ^
SyntaxError: invalid syntax
```

I see the extension has not been updated for many years, so i suspect it is nt compatible with current version.

Could you please consider updating it?

**Comment by birkenfeld** [comment]
Hey, nice to hear this has been useful to you!  I've ported the extension to Python 3 now.

It works with IPython 7, which is what I have here, please check if IPython 5.8 is also happy.

**Comment by 400thecat** [comment]
wow, that was fast reply.

With the new version, it now loads without errors, but conversions don't work:

```
Unit calculation and physics extensions activated.

In [1]: 1 cm // inch
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/lib/python3/dist-packages/IPython/terminal/ipapp.py", line 355, in start
    self.shell.mainloop()
  File "/usr/lib/python3/dist-packages/IPython/terminal/interactiveshell.py", line 495, in mainloop
    self.interact()
  File "/usr/lib/python3/dist-packages/IPython/terminal/interactiveshell.py", line 486, in interact
    self.run_cell(code, store_history=True)
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2646, in run_cell
    cell = self.input_transformer_manager.transform_cell(raw_cell)
  File "/usr/lib/python3/dist-packages/IPython/core/inputsplitter.py", line 597, in transform_cell
    self.push(cell)
  File "/usr/lib/python3/dist-packages/IPython/core/inputsplitter.py", line 640, in push
    out = self.push_line(line)
  File "/usr/lib/python3/dist-packages/IPython/core/inputsplitter.py", line 667, in push_line
    line = self.assemble_python_lines.push(line)
  File "/usr/lib/python3/dist-packages/IPython/core/inputtransformer.py", line 138, in push
    self.buf.append(line + '\n')
TypeError: can only concatenate list (not "str") to list

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by birkenfeld** [comment]
Thanks, that was an oversight; I pushed a fix.

**Comment by 400thecat** [comment]
everything works now.

thanks again

**Comment by birkenfeld** [comment]
Great! If you find anything else, please open another bug.
